# Nama alur kerja yang akan ditampilkan di tab Actions GitHub
name: Build Electron App

# Pemicu (trigger) untuk menjalankan alur kerja
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# Daftar pekerjaan (jobs) yang akan dijalankan
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      # 1. Checkout kode dari repositori
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Node.js secara eksplisit ke versi 20.x
      #    Ini adalah perbaikan untuk error "file .nvmrc does not exist"
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          # Versi Node.js yang akan digunakan. '20.x' akan menggunakan versi LTS terbaru dari v20.
          node-version: '20.x'

      # 3. Aktifkan Corepack untuk menggunakan Yarn
      - name: Enable Corepack
        run: corepack enable

      # 4. Install semua dependensi proyek menggunakan Yarn
      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      # 5. Jalankan perintah build spesifik untuk setiap OS
      - name: Build for Linux
        if: runner.os == 'Linux'
        run: yarn build:linux

      - name: Build for Windows
        if: runner.os == 'Windows'
        run: yarn build:win

      - name: Build for macOS
        if: runner.os == 'macOS'
        run: yarn build:mac

      # 6. Unggah hasil build sebagai artifak
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: youtube-music-${{ matrix.os }}
          path: |
            dist/*.exe
            dist/*.dmg
            dist/*.AppImage
            dist/*.deb
            dist/*.snap
            dist/builder-effective-config.yaml
